AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Step Functions workflow that does basic JSONata transformation.

Parameters:
  StateMachineName:
    Type: String
    Default: basic-transform-workflow
  
Resources:
  BasicTransformStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${StateMachineName}-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: BasicTransformJsonLoggingPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogDelivery
                  - logs:GetLogDelivery
                  - logs:UpdateLogDelivery
                  - logs:DeleteLogDelivery
                  - logs:ListLogDeliveries
                  - logs:PutResourcePolicy
                  - logs:DescribeResourcePolicies
                  - logs:DescribeLogGroups
                Resource: "*"

  BasicTransformStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Ref StateMachineName
      Type: STANDARD
      Role: !GetAtt BasicTransformStateMachineRole.Arn
      DefinitionUri: ../jsonata_step_function/basic_transform_function.asl.json

Outputs:
  StateMachineArn:
    Description: ARN of the Step Functions state machine
    Value: !Ref BasicTransformStateMachine

  StateMachineRoleArn:
    Description: IAM role used by Step Functions
    Value: !GetAtt BasicTransformStateMachineRole.Arn