AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Step Functions workflow that does basic JSONata transformation.

Parameters:
  StateMachineName:
    Type: String
    Default: demo-flow

  ConnectionArn:
    Type: String
    Description: ARN of the EventBridge API Destination connection to invoke the JSONata Transform API  
  
Resources:
  DemoFlowStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${StateMachineName}-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub '${StateMachineName}-LoggingPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogDelivery
                  - logs:GetLogDelivery
                  - logs:UpdateLogDelivery
                  - logs:DeleteLogDelivery
                  - logs:ListLogDeliveries
                  - logs:PutResourcePolicy
                  - logs:DescribeResourcePolicies
                  - logs:DescribeLogGroups
                Resource: "*"
        - PolicyName: !Sub '${StateMachineName}-ConnectionPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - events:RetrieveConnectionCredentials
                  - events:DescribeConnection
                Resource: !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:connection/*
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:events!connection/*
        - PolicyName: !Sub '${StateMachineName}-InvokeHttpEndpointPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:InvokeHTTPEndpoint
                Resource: "*"

  DemoFlowStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Ref StateMachineName
      Type: STANDARD
      Role: !GetAtt DemoFlowStateMachineRole.Arn
      DefinitionUri: ../jsonata_step_function/demo_flow_function.asl.json
      DefinitionSubstitutions:
        ConnectionArn: !Ref ConnectionArn

Outputs:
  StateMachineArn:
    Description: ARN of the Step Functions state machine
    Value: !Ref DemoFlowStateMachine

  StateMachineRoleArn:
    Description: IAM role used by Step Functions
    Value: !GetAtt DemoFlowStateMachineRole.Arn