AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Step Functions workflow that fetches users from dummyjson,
  maps them, and builds final response.

Parameters:
  StateMachineName:
    Type: String
    Default: huge-transform-workflow
  
  ConnectionArn:
    Type: String
    Description: ARN of the EventBridge API Destination connection to invoke the JSONata Transform API

Resources:
  
  HugeTransformStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${StateMachineName}-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: HugeTransformJsonLoggingPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogDelivery
                  - logs:GetLogDelivery
                  - logs:UpdateLogDelivery
                  - logs:DeleteLogDelivery
                  - logs:ListLogDeliveries
                  - logs:PutResourcePolicy
                  - logs:DescribeResourcePolicies
                  - logs:DescribeLogGroups
                Resource: "*"
        - PolicyName: HugeTransformConnectionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - events:RetrieveConnectionCredentials
                  - events:DescribeConnection
                Resource: !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:connection/*
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:events!connection/*
        - PolicyName: HugeTransformInvokeHttpEndpointPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:InvokeHTTPEndpoint
                Resource: "*"
        
  HugeTransformStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Ref StateMachineName
      Type: STANDARD
      Role: !GetAtt HugeTransformStateMachineRole.Arn
      DefinitionUri: ../jsonata_step_function/huge_transform_function.asl.json
      DefinitionSubstitutions:
        ConnectionArn: !Ref ConnectionArn

Outputs:
  StateMachineArn:
    Description: ARN of the Step Functions state machine
    Value: !Ref HugeTransformStateMachine

  StateMachineRoleArn:
    Description: IAM role used by Step Functions
    Value: !GetAtt HugeTransformStateMachineRole.Arn